version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: budget-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: budget_db
      MYSQL_USER: root
      MYSQL_PASSWORD: navaneeth
    ports:
      - "3307Scenario7

You are a Full-Stack Engineer in charge of deploying the Hospital Management System for a university healthcare portal. The project has two parts:

Â·         Backend (API): Spring Boot application that exposes /auth/signup and /auth/login are endpoints. Uses MySQL database and runs on localhost:8081. 

Backend url: https://github.com/suneethabulla/hospital-backend.git

Â·         Frontend: React (Vite) application that consumes these endpoints and displays Login and Signup pages. Dashboard page showing hospital modules (Doctors, Patients, Appointments) and runs on localhost:5173.

Frontend url: https://github.com/suneethabulla/hospital-frontend.git

Your task is to download, run, and deploy the system following CI/CD best practices.

1.      Clone the GitHub repository of the Hospital Management System onto your local machine. Execute locally and verify your frontend successful login and signup functionality by interacting with the backend API at http://localhost:8081

 

2.      Backend Deployment via Docker without Volume

 

Output verification: http://localhost:8080/auth/signup?username=testuser&email=testuser@gmail.com&password=admin123

:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    image: navaneethkrishna9/budget-backend:latest   # ðŸ‘ˆ changed line
    container_name: budget-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: navaneeth

  frontend:
    image: navaneethkrishna9/budget-frontend:latest   # ðŸ‘ˆ changed line
    container_name: budget-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data:
